name=SAMD21_WS2812B
version=1.0.4
author=Xorlent
maintainer=Xorlent <https://github.com/Xorlent>
sentence=Minimal WS2812B RGB LED library for SAMD21
paragraph=Ultra-lightweight library for controlling WS2812B RGB LEDs on SAMD21 microcontrollers (Arduino Zero, MKR family, Adafruit Feather M0, etc.)
category=Device Control
url=https://github.com/Xorlent/SAMD21_WS2812B
architectures=samd
depends=